# Generated by Django 3.0.6 on 2020-05-20 20:08

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ImageField(null=True, upload_to=core.models.post_image_file_path),
        ),
    ]
