# Generated by Django 3.0.6 on 2020-05-20 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_post_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='images',
            new_name='image',
        ),
    ]
